### ISSUE TITLE
512 compilation error 

### ISSUE THREAD

**Issue by chklopp** [RabbitBio/RabbitV#1]
We have tried to install RabbitV 0.1.0 on our server but got an "Illegal instruction" error on our Broadwell processors while compiling your code.

We have tried ot replace the avx512 compilation options  (-mavx512vl -mavx512bitalg -mavx512f -mavx512bw -mavx512vbmi2) by march=native, but got the following error.

$ make
g++ -c src/adaptertrimmer.cpp -o obj/adaptertrimmer.o -fopenmp -std=c++11 -g -O3 -flto -funroll-loops -march=native -I./inc  
g++ -c src/stats.cpp -o obj/stats.o -fopenmp -std=c++11 -g -O3 -flto -funroll-loops -march=native -I./inc  
src/stats.cpp: In member function ‘void Stats::statRead(Read*)’:
src/stats.cpp:340:61: warning: AVX512F vector return without AVX512F enabled changes the ABI [-Wpsabi]
  340 |     const __m512i const0X07 = _mm512_set1_epi32(constInt0X07);//创建一个0X07常数向量

Is there a solution to get around this?

**Comment by ZekunYin** [comment]
I believe that the handwritten avx512 intrinsics cause this  issue. We will try to fix it to support more architectures.

**Comment by LeiHaoa** [comment]
We have updated RabbitV for non-AVX512 machines.
Please update RabbitV and re-build it.

Please let us know if you have other issues while installing.
