### ISSUE TITLE
binary is available ?

### ISSUE THREAD

**Issue by kazumaxneo** [RabbitBio/RabbitV#2]
Hi. 
I am using AMD TR and am struggling with compiling.
Do you have any plans to place binaries in the release?

Yours sincerely,

**Comment by LeiHaoa** [comment]
Hi.
We are sorry about that. 
The Makefile truly has a bug when compiling.  We have updated the makefile.
Please update RabbitV and re-build it.

Please let us know if you have other issues while installing.

**Comment by kazumaxneo** [comment]
Hello,
Thank you for the response.
This time I was able to build !
