### ISSUE TITLE
Can't get it to work. 

### ISSUE THREAD

**Issue by raw937** [RabbitBio/RabbitV#3]
Hello, 

The SARS-CoV-2 beta isn't working nor is the Rabbituniq. 
It has failed to compile a couple of times. 
I will send you the error messages in the morning. 
Which gcc do you recommend?

**Comment by LeiHaoa** [comment]
Hi,
 We have tested gcc 9.4, gcc 8.5.0 and gcc 8.3.1, which gcc you have used? 
 Could you please paste the error message ??
